#!/bin/bash
# Job Name and Files (also --job-name)

#SBATCH -J john-seissol
#Output and error (also --output, --error):
#SBATCH -o ./%j.%x.out
#SBATCH -e ./%j.%x.err

# Wall clock limit:
#SBATCH --time=00:24:00
#SBATCH --no-requeue

#Setup of execution environment
#SBATCH --export=ALL
#SBATCH --account=pr63qo
#constraints are optional
#--constraint="scratch&work"
#SBATCH --partition=general

#Number of nodes and MPI tasks per node:
#SBATCH --nodes=40
#SBATCH --ntasks-per-node=1
module load slurm_setup

#Run the program:
export MP_SINGLE_THREAD=no
unset KMP_AFFINITY
export OMP_NUM_THREADS=94
export OMP_PLACES="cores(47)"

export XDMFWRITER_ALIGNMENT=8388608
export XDMFWRITER_BLOCK_SIZE=8388608
export SC_CHECKPOINT_ALIGNMENT=8388608

export SEISSOL_CHECKPOINT_ALIGNMENT=8388608
export SEISSOL_CHECKPOINT_DIRECT=1
export ASYNC_MODE=THREAD
export ASYNC_BUFFER_ALIGNMENT=8388608
source /etc/profile.d/modules.sh

echo $SLURM_NTASKS
ulimit -Ss 2097152
cd ../0
mpiexec -n $SLURM_NTASKS SeisSol_Release_sskx_5_elastic parameters.par
mpiexec -n $SLURM_NTASKS python -u /dss/dsshome1/0B/di46bak/SeisSol/postprocessing/science/GroundMotionParametersMaps/ComputeGroundMotionParametersFromSurfaceOutput_Hybrid.py output/loh1-surface.xdmf
cd ../1
mpiexec -n $SLURM_NTASKS SeisSol_Release_sskx_5_elastic parameters.par
mpiexec -n $SLURM_NTASKS python -u /dss/dsshome1/0B/di46bak/SeisSol/postprocessing/science/GroundMotionParametersMaps/ComputeGroundMotionParametersFromSurfaceOutput_Hybrid.py output/loh1-surface.xdmf